export const state = () => ({
  churches: [
    {
      img_url:
        'https://resources.openchurch.com/openchurch-1012112-CC0-matt-mclean-253049-PREVIEW.jpg',
      basic_info: {
        name: 'ABC Church',
        lat: 22.48661464351065,
        long: 35.5,
        phone: '+123475629374',
        website: 'https://www.acbchurch.org',
        email: 'church@abcchurch.org',
        country: 'Hidden',
        province: 'Hidden',
        city: 'Kowloon Tong',
        postcode: 'Hidden',
        denomination: 'Evangelical',
        leader: 'B',
        address: 'somewhere in the world',
        whatsapp: '+123475629374',
        languages: ['English', 'Mandarin'],
      },
      services: [
        {
          languages: ['Eng', '普'],
          weekday: 'Sun',
          start_time: '10:00:00',
          end_time: '11:30:00',
          max_people: 100,
          mode: 'In Person',
        },
      ],
      activities: ['Child', 'Teens', 'Adult', 'Small group'],
      remarks: 'Please contact the church leaders for location',
    },

    {
      img_url:
        'https://resources.openchurch.com/openchurch-1012112-CC0-matt-mclean-253049-PREVIEW.jpg',
      basic_info: {
        name: 'CMA Living Stones Church',
        lat: 22.48661464351065,
        long: 114.14475246187553,
        phone: '+85226718532',
        website: 'https://cmals.org.hk/',
        email: 'office@cmals.org.hk',
        country: 'Hong Kong',
        province: 'Hong Kong',
        city: 'Fanling',
        postcode: '',
        denomination: 'Evangelical',
        leader: 'Leung Tsz Yung',
        address: '粉嶺一鳴路23號牽晴間6座',
        whatsapp: '+85255362902',
        languages: ['Cantonese'],
      },
      services: [
        {
          languages: ['粵'],
          weekday: 'Sun',
          start_time: '09:00:00',
          end_time: '10:30:00',
          max_people: 50,
          mode: 'In Person',
        },
        {
          languages: ['粵'],
          weekday: 'Sun',
          start_time: '11:00:00',
          end_time: '12:30:00',
          max_people: 50,
          mode: 'In Person',
        },
        {
          languages: ['粵'],
          weekday: 'Sat',
          start_time: '17:00:00',
          end_time: '18:30:00',
          max_people: 50,
          mode: 'In Person',
        },
        {
          languages: ['粵'],
          weekday: 'Sun',
          start_time: '09:00:00',
          end_time: '10:30:00',
          max_people: 50,
          mode: 'In Person',
        },
      ],
      activities: [
        'Child',
        'Adult',
        'Small group',
        'Prayer Meeting',
        'Summer camp',
        'Mission Trip',
      ],
      remarks: '',
    },

    {
      img_url:
        'https://www.tccc.ca/wordpress/wp-content/uploads/2020/01/45th-mural-scaled.jpg',
      basic_info: {
        name: 'Toronto Christian Community Church',
        lat: 43.821978571268694,
        long: -79.32863676931458,
        phone: '+19054777533',
        website: 'http://www.tccc.ca/',
        email: 'admin@tccc.ca',
        country: 'Canada',
        province: 'Ontario',
        city: 'Markham',
        postcode: 'L3R 5A2',
        denomination: 'Evangelical',
        leader: 'Rev. Jonathan Chan',
        address: '100 Acadia Avenue, Markham, ON L3R 5A2',
        whatsapp: '',
        languages: ['English', 'Cantonese', 'Mandarin'],
      },
      services: [
        {
          languages: ['Eng'],
          weekday: 'Sun',
          start_time: '10:30:00',
          end_time: '',
          max_people: '',
          mode: 'Online',
        },
        {
          languages: ['粵'],
          weekday: 'Sun',
          start_time: '08:15:00',
          end_time: '',
          max_people: '',
          mode: 'Online',
        },
        {
          languages: ['粵'],
          weekday: 'Sat',
          start_time: '11:15:00',
          end_time: '',
          max_people: '',
          mode: 'Online',
        },
        {
          languages: ['普'],
          weekday: 'Sun',
          start_time: '09:40:00',
          end_time: '',
          max_people: 50,
          mode: 'Online',
        },
      ],
      activities: [
        'Child',
        'Teens',
        'Adult',
        'Youth worship',
        'Small group',
        'Prayer Meeting',
        'Summer camp',
        'Mission Trip',
      ],
      remarks: '',
    },
    {
      img_url:
        'https://resources.openchurch.com/openchurch-1012112-CC0-matt-mclean-253049-PREVIEW.jpg',
      basic_info: {
        name: 'EFG Church',
        lat: 22.48661464351065,
        long: 35.5,
        phone: '+123475629374',
        website: 'https://www.acbchurch.org',
        email: 'church@abcchurch.org',
        country: 'Hidden',
        province: 'Hidden',
        city: 'Kowloon Tong',
        postcode: 'Hidden',
        denomination: 'Evangelical',
        leader: 'B',
        address: 'somewhere in the world',
        whatsapp: '+123475629374',
        languages: ['English', 'Mandarin'],
      },
      services: [
        {
          languages: ['Eng', '普'],
          weekday: 'Sun',
          start_time: '10:00:00',
          end_time: '11:30:00',
          max_people: 100,
          mode: 'In Person',
        },
      ],
      activities: ['Child', 'Teens', 'Adult', 'Small group'],
      remarks: 'Please contact the church leaders for location',
    },

    {
      img_url:
        'https://resources.openchurch.com/openchurch-1012112-CC0-matt-mclean-253049-PREVIEW.jpg',
      basic_info: {
        name: 'CWB Chinese Church',
        lat: 22.48661464351065,
        long: 114.14475246187553,
        phone: '+85226718532',
        website: 'https://cmals.org.hk/',
        email: 'office@cmals.org.hk',
        country: 'Hong Kong',
        province: 'Hong Kong',
        city: 'Fanling',
        postcode: '',
        denomination: 'Evangelical',
        leader: 'Leung Tsz Yung',
        address: '粉嶺一鳴路23號牽晴間6座',
        whatsapp: '+85255362902',
        languages: ['Cantonese'],
      },
      services: [
        {
          languages: ['粵'],
          weekday: 'Sun',
          start_time: '09:00:00',
          end_time: '10:30:00',
          max_people: 50,
          mode: 'In Person',
        },
        {
          languages: ['粵'],
          weekday: 'Sun',
          start_time: '11:00:00',
          end_time: '12:30:00',
          max_people: 50,
          mode: 'In Person',
        },
        {
          languages: ['粵'],
          weekday: 'Sat',
          start_time: '17:00:00',
          end_time: '18:30:00',
          max_people: 50,
          mode: 'In Person',
        },
        {
          languages: ['粵'],
          weekday: 'Sun',
          start_time: '09:00:00',
          end_time: '10:30:00',
          max_people: 50,
          mode: 'In Person',
        },
      ],
      activities: [
        'Child',
        'Adult',
        'Small group',
        'Prayer Meeting',
        'Summer camp',
        'Mission Trip',
      ],
      remarks: '',
    },

    {
      img_url:
        'https://www.tccc.ca/wordpress/wp-content/uploads/2020/01/45th-mural-scaled.jpg',
      basic_info: {
        name: 'Kowloon Community Church',
        lat: 43.821978571268694,
        long: -79.32863676931458,
        phone: '+19054777533',
        website: 'http://www.tccc.ca/',
        email: 'admin@tccc.ca',
        country: 'Canada',
        province: 'Ontario',
        city: 'Markham',
        postcode: 'L3R 5A2',
        denomination: 'Evangelical',
        leader: 'Rev. Jonathan Chan',
        address: '100 Acadia Avenue, Markham, ON L3R 5A2',
        whatsapp: '',
        languages: ['English', 'Cantonese', 'Mandarin'],
      },
      services: [
        {
          languages: ['Eng'],
          weekday: 'Sun',
          start_time: '10:30:00',
          end_time: '',
          max_people: '',
          mode: 'Online',
        },
        {
          languages: ['粵'],
          weekday: 'Sun',
          start_time: '08:15:00',
          end_time: '',
          max_people: '',
          mode: 'Online',
        },
        {
          languages: ['粵'],
          weekday: 'Sat',
          start_time: '11:15:00',
          end_time: '',
          max_people: '',
          mode: 'Online',
        },
        {
          languages: ['普'],
          weekday: 'Sun',
          start_time: '09:40:00',
          end_time: '',
          max_people: 50,
          mode: 'Online',
        },
      ],
      activities: [
        'Child',
        'Teens',
        'Adult',
        'Youth worship',
        'Small group',
        'Prayer Meeting',
        'Summer camp',
        'Mission Trip',
      ],
      remarks: '',
    },
  ],
  church: {
    img_url:
      'https://resources.openchurch.com/openchurch-1012112-CC0-matt-mclean-253049-PREVIEW.jpg',
    basic_info: {
      name: 'ABC Church',
      lat: 22.48661464351065,
      long: 35.5,
      phone: '+123475629374',
      website: 'https://www.acbchurch.org',
      email: 'church@abcchurch.org',
      country: 'Hidden',
      province: 'Hidden',
      city: 'Kowloon Tong',
      postcode: 'Hidden',
      denomination: 'Evangelical',
      leader: 'B',
      address: 'somewhere in the world',
      whatsapp: '+123475629374',
      languages: ['English', 'Mandarin'],
    },
    services: [
      {
        languages: ['Eng', '普'],
        weekday: 'Sun',
        start_time: '10:00:00',
        end_time: '11:30:00',
        max_people: 100,
        mode: 'In Person',
      },
    ],
    activities: ['Child', 'Teens', 'Adult', 'Small group'],
    remarks: 'Please contact the church leaders for location',
  },
})

export const mutations = {
  setChurch(state, val) {
    state.church = val
    console.log('VUEX: set church to ', state.church)
  },
}
